language: cpp
sudo: required
compiler : g++

addons:
  apt:
    packages:
      - doxygen
      - cppcheck

script: 
    - mkdir build & cd build & cmake -DENABLE_COVERAGE=TRUE -Dgtest_force_shared_crt=TRUE  ..
    - cmake --build .

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"